name: Deploy Repository to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Validate app-config.json format
        run: |
          npm install -g ajv-cli
          for file in $(find . -path "*/app-config.json"); do
            ajv validate -s ./Template/app-config.schema.json -d "$file"
          done

      - name: Upload only app-config.json preserving path
        run: |
          aws s3 cp ./ s3://studiomk-app-assets/ \
            --recursive \
            --exclude "*" \
            --include "*/app-config.json" \
            --cache-control no-cache
